---
- name: Check lxd container
  shell: 
    executable: /bin/bash
    cmd: "/snap/bin/lxc list"
  register: remote_info
  ignore_errors: true

# - debug: msg="{{ remote_info.stdout }}"

- name: Create container
  shell:
    executable: /bin/bash
    cmd: "/snap/bin/lxc launch images:{{ image }} {{ item }}"
  when: not remote_info.stdout | regex_search('\s{{ item }}\s', ignorecase=True)
  with_items: "{{ containers }}"
