---
- name: Check lxd container
  shell: 
    executable: /bin/bash
    cmd: "/snap/bin/lxc list"
  register: remote_info
  ignore_errors: true

# - debug: msg="{{ remote_info.stdout }}"

- name: Create container
  shell:
    executable: /bin/bash
    cmd: "/snap/bin/lxc launch images:{{ image }} {{ item }}"
  with_items: "{{ containers }}"
  when:
    - remote_info.stdout.search("^{{ item }}$") == -1 
