- name: Config lxd server
  shell: 
    executable: /bin/bash
    cmd: |
      "{{ lxc_exec }} config set core.https_address={{ LXD_ADDR }}"
      "{{ lxc_exec }} config set core.trust_password={{ LXD_SERVER_PASS }}"
