- name: Config lxd server
  shell: 
    environment:
      LXC: "{{ lxc_exec }}"
    executable: /bin/bash
    cmd: |
      $LXC config set core.https_address={{ LXD_ADDR }}
      $LXC config set core.trust_password={{ LXD_SERVER_PASS }}
