---
# Variable configuration.
- include_tasks: variables.yml

- name: Set lxc executable environment
  environment:
    LXC: "{{ lxc_exec }}"

# Configure.
- import_tasks: container.yml

- include_tasks: user.yml
  loop: "{{ containers }}"
  loop_control:
    loop_var: container
