---
- name: LXD | Create user Centos
  shell:
    cmd: lxc exec {{ container }} -- sh -c 'sudo adduser {{ user }}'
  ignore_errors: yes
  when: image.find("centos") != -1

- name: LXD | Create user Ubuntu
  shell:
    cmd: lxc exec {{ container }} -- sh -c 'sudo adduser --disabled-password --gecos "" {{ user }}'
  ignore_errors: yes
  when: image.find("ubuntu") != -1
  
- name: "Check user in container"
  shell: 
    cmd: lxc exec {{ container }} -- sh -c 'cat /etc/sudoers'
  register: user_info
  ignore_errors: yes
  become: yes

- name: LXD | Add user to sudoer
  shell:
    cmd: |
      lxc exec {{ container }} -- sh -c 'sudo echo "{{ user }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
  when: user_info.stdout.find("{{ user }}") == -1
