---
- name: Create user Centos
  environment:
    LXC: "{{ lxc_exec }}"
  shell:  
    executable: /bin/bash
    cmd: $LXC exec {{ container }} -- sh -c 'sudo adduser {{ user }}'
  ignore_errors: true
  when: image.find("centos") != -1

- name: Create user Ubuntu
  environment:
    LXC: "{{ lxc_exec }}"
  shell:  
    executable: /bin/bash
    cmd: $LXC exec {{ container }} -- sh -c 'sudo adduser --disabled-password --gecos "" {{ user }}'
  ignore_errors: true
  when: image.find("ubuntu") != -1
  
- name: "Check user in container"
  environment:
    LXC: "{{ lxc_exec }}"
  shell: 
    executable: /bin/bash
    cmd: $LXC exec {{ container }} -- sh -c 'cat /etc/sudoers'
  register: user_info
  ignore_errors: true

- name: Add user to sudoer
  environment:
    LXC: "{{ lxc_exec }}"
  shell: 
    executable: /bin/bash
    cmd: |
      $LXC exec {{ container }} -- sh -c 'sudo echo "{{ user }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
  when: not user_info.stdout | regex_search('(^|\s|\n){{ user }}\s', ignorecase=True)
