---
- name: Create user Centos
  shell:  
    executable: /bin/bash
    cmd: "/snap/bin/lxc exec {{ container }} -- sh -c 'sudo adduser {{ user }}'"
  ignore_errors: true
  when: image.find("centos") != -1

- name: Create user Ubuntu
  shell:  
    executable: /bin/bash
    cmd: /snap/bin/lxc exec {{ container }} -- sh -c 'sudo adduser --disabled-password --gecos "" {{ user }}'
  ignore_errors: true
  when: image.find("ubuntu") != -1
  
- name: "Check user in container"
  shell: 
    executable: /bin/bash
    cmd: "/snap/bin/lxc exec {{ container }} -- sh -c 'cat /etc/sudoers'"
  register: user_info
  ignore_errors: true

- name: Add user to sudoer
  shell: 
    executable: /bin/bash
    cmd: |
      /snap/bin/lxc exec {{ container }} -- sh -c 'sudo echo "{{ user }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
  when: not user_info.stdout | regex_search('(^|\s|\n){{ user }}\s', ignorecase=True)
